---
#title: "Metabolites_secretion"
#author: "Sònia"
#date: "2020 M07 17"
#output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
setwd("P:/MG/Paper/Metabolomics")
metadata <- read.csv("metabolomics2.csv",header=T, row.names=1, sep=",")
```


```{r}
#install.packages("matrixStats")
library(tidyverse)
library(pheatmap)
library(RColorBrewer)
library(matrixStats)
library(ggplot2)
```

```{r}
##No normalization of dataset
#Just to see whether replicates group together
pheatmap(as.matrix(metadata[,2:28]), color = colorRampPalette(rev(brewer.pal(n = 8, name = "Spectral")))(100),legend=TRUE, main="", angle_col = 45, fontsize_row = 8, fontsize_col=10,cellwidth = 15, width=15, height = 10)
```
```{r}
#Transform Row index into 1st column called "Metabolite"
  library(dplyr)
data1 <- tibble::rownames_to_column(metadata, "Metabolite")
```

```{r}
#median of replicates
data <- data1 %>% 
  mutate(MO_wo_1 = rowMedians(as.matrix(data1[,2:4])))%>%
  mutate(MO_wo_2 = rowMedians(as.matrix(data1[,5:7])))%>%
  mutate(MO_wo_3 = rowMedians(as.matrix(data1[,8:10])))%>%
  mutate(pMGLMO_K7_DB200_1 = rowMedians(as.matrix(data1[,11:13])))%>%
  mutate(pMGLMO_K7_DB200_2 = rowMedians(as.matrix(data1[,14:16])))%>%
  mutate(pMGLMO_K7_DB200_3 = rowMedians(as.matrix(data1[,17:19])))%>%
  mutate(pMGLMO_163_DB304_1 = rowMedians(as.matrix(data1[,20:22])))%>%
  mutate(pMGLMO_163_DB304_2 = rowMedians(as.matrix(data1[,23:25])))%>%
  mutate(pMGLMO_163_DB304_3 = rowMedians(as.matrix(data1[,26:28])))%>%
  mutate(pMGLMO_EPI_DB201_1 = rowMedians(as.matrix(data1[,29:31])))%>%
  mutate(pMGLMO_EPI_DB201_2 = rowMedians(as.matrix(data1[,32:34])))%>%
  mutate(pMGLMO_EPI_DB201_3 = rowMedians(as.matrix(data1[,35:37])))
```
```{r}
column_to_rownames(data,var="Metabolite")->data2
data3<-data2[,37:48]
```

```{r}
#With the pooled data for a pooled heatmap
datapooled<-data1%>%
  mutate(Midbrain_organoids = rowMedians(as.matrix(data1[,2:10])))%>%
  mutate(Assembloids_K7 = rowMedians(as.matrix(data1[,11:19])))%>%
  mutate(Assembloids_163 = rowMedians(as.matrix(data1[,20:28])))%>%
  mutate(Assembloids_EPI = rowMedians(as.matrix(data1[,29:37])))
  
column_to_rownames(datapooled,var="Metabolite")-> datapooled2
datapooled3<-datapooled2[,37:40]

```
'
```{r}
# Most basic error bar
#ggplot(data) +
#    geom_bar( aes(x=name, y=value), stat="identity", fill="skyblue", alpha=0.7) +
 #   geom_errorbar( aes(x=name, ymin=value-sd, ymax=value+sd), width=0.4, colour="orange", alpha=0.9, size=1.3)

```


```{r}
#rename cell lines
#colnames(data3)<-c('Ctrl_1', 'Ctrl_2', 'Ctrl_3', 'IPD_1', 'IPD_2', 'IPD_4', 'IPD_3', 'IPD_5', 'IPD_6')

#normalization
Z_Normalize<-function(x){return((x-mean(x))/(sd(x)))}

NormalisedData_Zscore = t(apply(as.matrix(data3),1,Z_Normalize))

pheatmap(as.matrix(NormalisedData_Zscore), color = colorRampPalette(rev(brewer.pal(n = 8, name = "Spectral")))(100),legend=TRUE, main="Extracellular metabolites", angle_col = 45, fontsize_row = 7, fontsize_col=10,cellwidth = 30, width=30, height = 15)


#Now with pooled samples
Z_Normalize<-function(x){return((x-mean(x))/(sd(x)))}

NormalisedData_Zscore = t(apply(as.matrix(datapooled3),1,Z_Normalize))

heatmap <-pheatmap(as.matrix(NormalisedData_Zscore), color = colorRampPalette(rev(brewer.pal(n = 8, name = "Spectral")))(100),legend=TRUE, angle_col = 45, fontsize_row = 7, fontsize_col=10,cellwidth = 30, width=30, height = 15)

print(heatmap_pooled)
  ggsave(paste0(Sys.Date(),"Extracellular metabolites.pdf"), plot=heatmap)
```


###PCA
```{r}
library(factoextra)

t_datapooled3 <- t(datapooled3)

res.pca <- prcomp(t_datapooled3, scale = TRUE)
summary(res.pca)
fviz_eig(res.pca, addlabels = TRUE, ylim = c(0, 70)) ### to see the importance of each component

#eig.val <- get_eigenvalue(res.pca)
#eig.val
```
```{r}
#install.packages("corrplot")
library("corrplot")
var <- get_pca_var(res.pca)
#corrplot(var$cos2, is.corr=FALSE)
#corrplot(var$contrib, is.corr=FALSE)  
fviz_contrib(res.pca, choice = "var", axes = 1, top = 10) ###visualise top 10 contributors/mets to the variance given by 1st dimension
fviz_contrib(res.pca, choice = "var", axes = 2, top = 10) ###visualise top 10 contributors/mets to the variance given by 2nd dimension
#fviz_contrib(res.pca, choice = "var", axes = 1:2, top = 10)
```

```{r}
fviz_pca_ind(res.pca,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800","#FC4E07","2E9FDF"),#"#FC4E07"
             repel = TRUE )    # Avoid text overlapping
```


```{r}
fviz_pca_var(res.pca,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07", "2E9FDF"),
             legend.title = "Contribution",
             repel = TRUE     # Avoid text overlapping
             )
```
```{r}
fviz_pca_biplot(res.pca, repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969"  # Individuals color
                )
```
```{r}
#Try it with the separate batches
  Condition <- as.factor(c(rep("MO_wo1",1),rep("MO_wo2",2),rep("MO_wo3",3),rep("pMGLMO_K7_DB200_1",4),rep("pMGLMO_K7_DB200_2",5),rep("pMGLMO_K7_DB200_3",6),rep("pMGLMO_163_DB304_1",7),rep("pMGLMO_163_DB304_2",8),rep("pMGLMO_163_DB304_3",9),rep("pMGLMO_EPI_DB201_1",10),rep("pMGLMO_EPI_DB201_2",11),rep("pMGLMO_EPI_DB201_3",12)))
g <- fviz_pca_ind(res.pca, 
             col.ind = Condition, # color by groups
             palette = c("#B2FF66",  "#66FF66", "#66FFB2",  "#99FFFF", "#99CCFF","#9999FF","#FFCC99","#FFB266","#FF9933","#FF99CC","#FF66B2","#FF3399"),
             addEllipses = TRUE, # Concentration ellipses
             ellipse.type = "confidence",
             legend.title = "Condition",
             geom.ind =  "text",
             labelsize=9,
             repel = TRUE
             )
ggpubr::ggpar(g,
              font.ytickslab = 24, font.xtickslab = 24, font.x = 24, font.y = 24, font.legend = 24, title="")

```


###Ttest with Welchs correction
```{r}
pvalue=sapply(1:nrow(metdata),function(i)
{t.test(Ctrl[i,],iPD[i,])$p.value}
)
FC <- apply(iPD,1,mean)/apply(Ctrl,1,mean)
FDR <- p.adjust(pvalue, method = "BH")

CtrlvsiPD = cbind(FC, pvalue, FDR) 
#write.csv(CtrlvsiPD,file="Ttest.csv")

CtrlvsiPD<-data.frame(CtrlvsiPD)
Significance<-CtrlvsiPD[with(CtrlvsiPD,order(pvalue)),]
head(Significance)
#write.csv(Significance, 'Ttest_hNESCs_Polar.csv')

```
```{r}
library(ggplot2)
library(ggpubr)
tCtrl_iPD %>% as_tibble(tCtrl_iPD, rownames='Labels') %>%
  mutate(Condition = case_when(str_detect(Labels, 'IPD') ~ 'IPD', str_detect(Labels, 'Ctrl') ~ 'Ctrl',
                             TRUE ~ 'test'))  -> metdataT
```

```{r}
my_sum <- metdataT %>%
  group_by(Condition) %>%
  summarise( 
    n=n(),
    mean=mean(x3Hydroxymethylglutaric_acid),
    sd=sd(x3Hydroxymethylglutaric_acid)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
```

```{r}
t.test(x3Hydroxymethylglutaric_acid~Condition, data=metdataT)
```

```{r}
ggplot(my_sum) +
    geom_bar(aes(x = Condition, y = mean, fill=Condition), stat="identity",alpha=1, width = 0.6) +
  scale_fill_manual(values=c('dark grey', 'grey38'))+
    geom_errorbar( aes(x = Condition, ymin = mean-sd, ymax=mean+sd), width=0.1, colour="black", alpha=0.9, size=1.3)+
  theme_classic()+
    labs(title="3-Hydroxymethylglutaric acid", y = "Relative abundance")+
    theme(plot.title=element_text(size=32, face="bold", hjust = 0.1),
        axis.text.x=element_text(size = 30, face = "bold"), 
        axis.title.x=element_blank(), axis.title.y=element_text(size=34),axis.text.y=element_text(size=30), legend.text = element_text(size=30), legend.title = element_text(size=30))

```



```{r}
###Pyridine-2,3-dicarboxylic acid
my_sum <- metdataT %>%
  group_by(Condition) %>%
  summarise( 
    n=n(),
    mean=mean(Pyridinedicarboxylic_acid),
    sd=sd(Pyridinedicarboxylic_acid)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))

t.test(Pyridinedicarboxylic_acid~Condition, data=metdataT)

ggplot(my_sum) +
    geom_bar(aes(x = Condition, y = mean, fill=Condition), stat="identity",alpha=1, width = 0.6) +
  scale_fill_manual(values=c('dark grey', 'grey38'))+
    geom_errorbar( aes(x = Condition, ymin = mean-sd, ymax=mean+sd), width=0.1, colour="black", alpha=0.9, size=1.3)+
  theme_classic()+
    labs(title="Pyridine-2,3-dicarboxylic acid", y = "Relative abundance")+
    theme(plot.title=element_text(size=32, face="bold", hjust = 0.1),
        axis.text.x=element_text(size = 30, face = "bold"), 
        axis.title.x=element_blank(), axis.title.y=element_text(size=34),axis.text.y=element_text(size=30), legend.text = element_text(size=30), legend.title = element_text(size=30))
```

#boxplot
```{r}
metdataT %>% 
  mutate(Cellline = case_when  (str_detect(Labels, 'Ctrl_1') ~ 'CTRL39',
                               str_detect(Labels, 'Ctrl_2') ~ 'CTRL48',
                               str_detect(Labels, 'Ctrl_3')~  'CTRL56',
                               str_detect(Labels, 'IPD_6')~  'IPD30C9',
                               str_detect(Labels, 'IPD_5')~  'IPD30C2',
                               str_detect(Labels, 'IPD_4')~  '2490',
                               str_detect(Labels, 'IPD_1')~  'IPD12',
                               str_detect(Labels, 'IPD_2')~  'IPD13',
                               str_detect(Labels, 'IPD_3')~  'IPD28',
                               TRUE ~ 'none'))%>%
  mutate(Condition = case_when (str_detect(Labels, 'Ctrl') ~ 'CTRL',
                               str_detect(Labels, 'IPD') ~ 'IPD',
                               TRUE ~ 'none'))->ToPlot

feature_names <- colnames(ToPlot[,2:50])  

```

```{r}

for (i in 1:length(feature_names)) {
ToPlot %>%
  pivot_longer(cols=feature_names, names_to = "feature", values_to = "value") %>%
  filter(feature %in% feature_names[i]) %>%
  ggplot(aes(x = Condition, y =value))+
    geom_boxplot(aes(fill=Condition),width=0.5)+
    scale_fill_manual(values=c('light grey', 'dark grey'))+
    #geom_point(aes(color=cell_line, shape=Section), size=5)
    geom_point(aes(color=Cellline), size=3)+
     labs(x     ="",
       y     = "Relative abundance",
       fill  = "Condition",
       title = paste(feature_names[i])) +
    ggpubr::stat_compare_means(aes(group = Condition), method = 't.test', label="p.signif", label.x = 1.5)+
    theme_bw() +
    theme(plot.title=element_text(size=15, face="bold", hjust=0.5),
          axis.text.x=element_text(size = 10, face = "bold", angle=45), 
          axis.title.x=element_blank(), axis.title.y=element_text(size=12))  -> p
  t<- cowplot::ggdraw(cowplot::add_sub(p, "t.test, ***p=0.001, **p=0.01, *p=0.05",hjust=-0.5, size=9))
  print(t)
}
```

```{r}
###creating a Volcano plot

df <- as.data.frame(CtrlvsiPD)
df1 <- as.data.frame(log(df$FC,2))
df2 <- as.data.frame(-log(df$FDR,10))


mets <- rownames(CtrlvsiPD)
data <- cbind.data.frame(mets,df,df1)
colnames(data) <- c("mets","FC", "pvalue", "FDR", "log2FC")

```


```{r}
library(ggrepel)
data$Significant <- ifelse(data$pvalue < 0.05, "pvalue < 0.05", "Not significant")
ggplot(data, aes(x = log2FC, y = -log10(pvalue))) +
  geom_point(aes(color = Significant), size=4) +
  scale_color_manual(values = c("black", "red")) +
    labs( x = "log2FoldChange")+
   theme_bw(base_size = 20) + theme(legend.position = "right", legend.title = element_blank(), axis.title.x=element_text(size = 28), 
axis.title.y=element_text(size=28), legend.text=element_text(size=16), text=element_text(size=34))+
  geom_text_repel(
    data = subset(data, pvalue < 0.05),
    aes(label = mets),
    size = 5,
    box.padding = unit(0.35, "lines"),
    point.padding = unit(0.3, "lines")
  )
```
```{r}
data$Significant <- ifelse(data$pvalue < 0.05, "pvalue < 0.05", "Not significant")
ggplot(data, aes(x = log2FC, y = -log10(pvalue))) +
  geom_point(aes(color = Significant), size=4) +
  scale_color_manual(values = c("black", "red")) +
    labs( x = "log2FoldChange")+
  theme_bw(base_size = 20) + theme(legend.position = c(0.75,0.85), legend.title = element_blank(), axis.title.x=element_text(size = 28), 
axis.title.y=element_text(size=28), legend.text=element_text(size=24), text=element_text(size=34))
  
  
```


